"""create table

Revision ID: 87e029392ecd
Revises: 
Create Date: 2024-04-04 14:42:31.663251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e029392ecd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('ownername', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('is_verifide', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('user_email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('business',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('business_description', sa.String(length=300), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('owner_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Product',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('original_price', sa.DECIMAL(), nullable=True),
    sa.Column('new_price', sa.DECIMAL(), nullable=True),
    sa.Column('percentage_discount', sa.Integer(), nullable=True),
    sa.Column('offer_expiration_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('product_image', sa.String(length=200), nullable=True),
    sa.Column('date_published', sa.TIMESTAMP(), nullable=True),
    sa.Column('business_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Product')
    op.drop_table('business')
    op.drop_table('users')
    op.drop_table('owner')
    # ### end Alembic commands ###
